name: Run Pyrogram Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 可以根据需要修改 Python 版本

    - name: Install dependencies
      run: |
        pip install pyrogram tgcrypto

    - name: Print environment variables
      run: |
        echo "API_ID=${{ secrets.API_ID }}"
        echo "API_HASH=${{ secrets.API_HASH }}"
        echo "BOT_USERNAME=${{ secrets.BOT_USERNAME }}"

    - name: Run Pyrogram script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      run: |
        python qinadoa.py
